export enum AccountActionType {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  REFRESH_TOKEN = "REFRESH_TOKEN",
  GET_USER_INFO = "USER_INFO",
  EXTERNAL_LOGIN = "EXTERNAL_LOGIN",
  CHANGE_LOADING = "CHANGE_LOADING",
  GET_NOTIFICATIONS = "GET_NOTIFICATIONS",
  READ_NOTIFICATION = "READ_NOTIFICATION",
  GET_LABEL_OPTIONS = "GET_LABEL_OPTIONS",
}
